// <auto-generated />
using System;
using Domus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Domus.Infrastructure.Migrations
{
    [DbContext(typeof(DomusDbContext))]
    [Migration("20260728005352_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domus.Domain.Attempts.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<long>("TotalTimeMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId", "RoundId");

                    b.HasIndex("RoundId", "ParticipantId")
                        .IsUnique()
                        .HasDatabaseName("UX_Attempts_RoundParticipant");

                    b.HasIndex("RoundId", "TotalPoints", "TotalTimeMs");

                    b.ToTable("Attempts", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Attempts.AttemptAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<int>("BasePoints")
                        .HasColumnType("integer");

                    b.Property<long>("ElapsedMs")
                        .HasColumnType("bigint");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuestionOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SelectedOptionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ServedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SpeedBonus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SelectedOptionId");

                    b.HasIndex("AttemptId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("UX_AttemptAnswers_AttemptQuestion");

                    b.HasIndex("AttemptId", "QuestionOrder");

                    b.HasIndex("QuestionId", "Outcome");

                    b.ToTable("AttemptAnswers", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Participants.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedDisplayName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowInRanking")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IsRemoved");

                    b.HasIndex("NormalizedDisplayName")
                        .IsUnique();

                    b.ToTable("Participants", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Rounds.AnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "Order")
                        .IsUnique();

                    b.ToTable("AnswerOptions", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Rounds.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Explanation")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("RoundId", "Order")
                        .IsUnique();

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Rounds.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ClosesAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OpensAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "WeekNumber")
                        .IsUnique();

                    b.HasIndex("SeasonId", "Status", "OpensAt");

                    b.HasIndex("Status", "OpensAt", "ClosesAt");

                    b.ToTable("Rounds", null, t =>
                        {
                            t.HasCheckConstraint("CK_Rounds_Scoring", "\"Scoring_PointsPerCorrectAnswer\" BETWEEN 1 AND 100 AND \"Scoring_MaxSpeedBonus\" BETWEEN 0 AND 50 AND \"Scoring_QuestionTimeLimitSeconds\" BETWEEN 10 AND 300");

                            t.HasCheckConstraint("CK_Rounds_Window", "\"ClosesAt\" > \"OpensAt\"");
                        });
                });

            modelBuilder.Entity("Domus.Domain.Seasons.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasDatabaseName("UX_Seasons_SingleActive")
                        .HasFilter("\"Status\" = 1");

                    b.ToTable("Seasons", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Seasons.SeasonPodiumEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<long>("TotalTimeMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "Position")
                        .IsUnique();

                    b.ToTable("SeasonPodiumEntries", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Settings.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .IsDescending();

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Settings.GcSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("GcName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("InviteRotatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedInviteCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("GcSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_GcSettings_Singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("Domus.Infrastructure.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domus.Domain.Attempts.Attempt", b =>
                {
                    b.HasOne("Domus.Domain.Participants.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domus.Domain.Rounds.Round", null)
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domus.Domain.Rounds.RoundScoringSettings", "Scoring", b1 =>
                        {
                            b1.Property<Guid>("AttemptId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxSpeedBonus")
                                .HasColumnType("integer")
                                .HasColumnName("Scoring_MaxSpeedBonus");

                            b1.Property<int>("PointsPerCorrectAnswer")
                                .HasColumnType("integer")
                                .HasColumnName("Scoring_PointsPerCorrectAnswer");

                            b1.Property<int>("QuestionTimeLimitSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("Scoring_QuestionTimeLimitSeconds");

                            b1.HasKey("AttemptId");

                            b1.ToTable("Attempts");

                            b1.WithOwner()
                                .HasForeignKey("AttemptId");
                        });

                    b.Navigation("Scoring")
                        .IsRequired();
                });

            modelBuilder.Entity("Domus.Domain.Attempts.AttemptAnswer", b =>
                {
                    b.HasOne("Domus.Domain.Attempts.Attempt", null)
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domus.Domain.Rounds.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domus.Domain.Rounds.AnswerOption", null)
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Domus.Domain.Participants.Participant", b =>
                {
                    b.HasOne("Domus.Infrastructure.Identity.AppUser", null)
                        .WithOne()
                        .HasForeignKey("Domus.Domain.Participants.Participant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domus.Domain.Rounds.AnswerOption", b =>
                {
                    b.HasOne("Domus.Domain.Rounds.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domus.Domain.Rounds.Question", b =>
                {
                    b.HasOne("Domus.Domain.Rounds.Round", null)
                        .WithMany("Questions")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domus.Domain.Rounds.Round", b =>
                {
                    b.HasOne("Domus.Domain.Seasons.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domus.Domain.Rounds.Lesson", "Lesson", b1 =>
                        {
                            b1.Property<Guid>("RoundId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Lesson_Content");

                            b1.Property<string>("ExternalUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("Lesson_ExternalUrl");

                            b1.Property<string>("ScriptureReference")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("Lesson_ScriptureReference");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("Lesson_Title");

                            b1.HasKey("RoundId");

                            b1.ToTable("Rounds");

                            b1.WithOwner()
                                .HasForeignKey("RoundId");
                        });

                    b.OwnsOne("Domus.Domain.Rounds.RoundScoringSettings", "Scoring", b1 =>
                        {
                            b1.Property<Guid>("RoundId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxSpeedBonus")
                                .HasColumnType("integer")
                                .HasColumnName("Scoring_MaxSpeedBonus");

                            b1.Property<int>("PointsPerCorrectAnswer")
                                .HasColumnType("integer")
                                .HasColumnName("Scoring_PointsPerCorrectAnswer");

                            b1.Property<int>("QuestionTimeLimitSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("Scoring_QuestionTimeLimitSeconds");

                            b1.HasKey("RoundId");

                            b1.ToTable("Rounds");

                            b1.WithOwner()
                                .HasForeignKey("RoundId");
                        });

                    b.Navigation("Lesson")
                        .IsRequired();

                    b.Navigation("Scoring")
                        .IsRequired();
                });

            modelBuilder.Entity("Domus.Domain.Seasons.SeasonPodiumEntry", b =>
                {
                    b.HasOne("Domus.Domain.Seasons.Season", null)
                        .WithMany("Podium")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Domus.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Domus.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Domus.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domus.Domain.Attempts.Attempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Domus.Domain.Rounds.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Domus.Domain.Rounds.Round", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Domus.Domain.Seasons.Season", b =>
                {
                    b.Navigation("Podium");
                });
#pragma warning restore 612, 618
        }
    }
}
